version: "3.4"

networks:
  traefik_web:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    working_dir: /backend/
    volumes:
      - ./backend/:/backend/
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks: [traefik_web, default]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-goodfood.rule=Host(`api-goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.api-goodfood.entrypoints=http"

      - "traefik.http.routers.api-goodfood-secured.rule=Host(`api-goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.api-goodfood-secured.entrypoints=https"
      - "traefik.http.routers.api-goodfood-secured.tls.certresolver=tls"

  database:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - ./backend:/backend

  mail:
    image: maildev/maildev
    restart: always
    networks: [traefik_web, default]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail-goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.mail.entrypoints=http"

      - "traefik.http.routers.mail-secured.rule=Host(`mail-goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.mail-secured.entrypoints=https"
      - "traefik.http.routers.mail-secured.tls.certresolver=tls"

      - "traefik.http.services.mail-secured.loadbalancer.server.port=80"

  frontend:
    image: node:lts-alpine3.13
    restart: always
    volumes:
      - ./frontend:/var/www/app
    working_dir: /var/www/app
    command: yarn start
    environment:
      - HOST=0.0.0.0
    networks: [traefik_web, default]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-goodfood.rule=Host(`goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.frontend-goodfood.entrypoints=http"

      - "traefik.http.routers.frontend-goodfood-secured.rule=Host(`goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.frontend-goodfood-secured.entrypoints=https"
      - "traefik.http.routers.frontend-goodfood-secured.tls.certresolver=tls"

      - "traefik.http.services.frontend-goodfood-secured.loadbalancer.server.port=3000"

  frontend-admin:
    image: node:lts-alpine3.13
    restart: always
    volumes:
      - ./frontend-admin:/var/www/app
    working_dir: /var/www/app
    command: yarn start
    environment:
      - HOST=0.0.0.0
    networks: [traefik_web, default]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-admin-goodfood.rule=Host(`admin-goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.frontend-admin-goodfood.entrypoints=http"

      - "traefik.http.routers.frontend-admin-goodfood-secured.rule=Host(`admin-goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.frontend-admin-goodfood-secured.entrypoints=https"
      - "traefik.http.routers.frontend-admin-goodfood-secured.tls.certresolver=tls"

      - "traefik.http.services.frontend-admin-goodfood-secured.loadbalancer.server.port=3000"
