version: "3.4"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    working_dir: /backend/
    volumes:
      - ./backend/:/backend/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
      - mail

  database:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/backend
    #    ports:
    #      - "9000:9000"

  composer:
    build:
      context: .
      dockerfile: composer.Dockerfile
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null

  mail:
    image: maildev/maildev
    ports:
      - "1080:80"
    #      - "1025:25"

  # TODO dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  alpine:
    image: composer:latest
    restart: always
    volumes:
      - ./:/src
    command: tail -f /dev/null
    working_dir: /src/

  # ----------------

  react:
    build:
      context: .
      dockerfile: next.Dockerfile
    ports: [8000:3000]
    volumes:
      - ./frontend:/app
    working_dir: /app/
    command: sh -c "([ ! -d 'node_modules' ] && yarn) ; yarn dev"
