version: "3.4"

networks:
  traefik_web:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    working_dir: /backend/
    volumes:
      - ./backend/:/backend/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks: [traefik_web, default]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-goodfood.rule=Host(`api.goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.api-goodfood.entrypoints=http"

      - "traefik.http.routers.api-goodfood-secured.rule=Host(`api.goodfood.alexandre-hublau.com`)"
      - "traefik.http.routers.api-goodfood-secured.entrypoints=https"
      - "traefik.http.routers.api-goodfood-secured.tls.certresolver=tls"

  database:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/backend

  composer:
    build:
      context: .
      dockerfile: composer.Dockerfile
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    # TODO: remove :fresh --seed in real production
    command: sh -c "wait-for-it.sh database:5432 -- php artisan migrate:fresh --seed && tail -f /dev/null"

  # mail:
  #   image: maildev/maildev
  #   #      - "1025:25"
  #   networks: [traefik_web, default]

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  # Commentaires temporaires
  # react:
    # build:
      # context: .
      # dockerfile: next.Dockerfile
    # volumes:
      # - ./frontend:/app
    # working_dir: /app/
    # command: sh -c "([ ! -d 'node_modules' ] && yarn) ; yarn dev"
    # networks: [traefik_web]
    # env_file:
      # - frontend/.env
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.goodfood.rule=Host(`goodfood.alexandre-hublau.com`)"
      # - "traefik.http.routers.goodfood.entrypoints=http"
 
      # - "traefik.http.routers.goodfood-secured.rule=Host(`goodfood.alexandre-hublau.com`)"
      # - "traefik.http.routers.goodfood-secured.entrypoints=https"
      # - "traefik.http.routers.goodfood-secured.tls.certresolver=tls"
 
      # - "traefik.http.services.goodfood-secured.loadbalancer.server.port=3000"

      # - "traefik.http.routers.goodfood-secured.middlewares=beta-prefix@docker"
      # - "traefik.http.middlewares.beta-prefix.stripprefix.prefixes=/beta"
